{"name": "test_login_negative", "status": "broken", "statusDetails": {"message": "TypeError: 'WebDriver' object is not callable", "trace": "Setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5faad6898388f1a7c0da18161d16c9fe\")>\n\n    @pytest.mark.negative\n    def test_login_negative(Setup):\n>       driver = Setup()\nE       TypeError: 'WebDriver' object is not callable\n\ntest_vwo_login.py:22: TypeError"}, "start": 1728028862448, "stop": 1728028862449, "uuid": "f582fd05-2634-4d81-b26e-cbf9364d5c2c", "historyId": "8be6628af41c999eb267bfd17245a1df", "testCaseId": "8be6628af41c999eb267bfd17245a1df", "fullName": "tests.vwoLoginTests.test_vwo_login#test_login_negative", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "DESKTOP-O5T1HPJ"}, {"name": "thread", "value": "11240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}