{"name": "test_login_negative", "status": "broken", "statusDetails": {"message": "AttributeError: module 'lib2to3.pgen2.driver' has no attribute 'find_element'", "trace": "Setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c77c3c975b579ce8e4ff332b4efc9aeb\")>\n\n    def test_login_negative(Setup):\n        login = LoginPage(driver)\n>       login.login_to_vwo(email=\"vwo@app.vwo.com\", pwd=\"admin\")\n\ntest_vwo_login.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pageObjects\\loginPage.py:42: in login_to_vwo\n    self.get_email_address().send_keys(email)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.pageObjects.loginPage.LoginPage object at 0x000001B3C6C49210>\n\n    def get_email_address(self):\n>       return self.driver.find_element(*LoginPage.email_address)\nE       AttributeError: module 'lib2to3.pgen2.driver' has no attribute 'find_element'\n\n..\\pageObjects\\loginPage.py:22: AttributeError"}, "start": 1727353964619, "stop": 1727353964620, "uuid": "ef033226-adc8-4d24-b235-8b6924920a9f", "historyId": "8be6628af41c999eb267bfd17245a1df", "testCaseId": "8be6628af41c999eb267bfd17245a1df", "fullName": "tests.vwoLoginTests.test_vwo_login#test_login_negative", "labels": [{"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "DESKTOP-O5T1HPJ"}, {"name": "thread", "value": "13232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}