{"name": "test_login_negative", "status": "broken", "statusDetails": {"message": "TypeError: 'WebDriver' object is not callable", "trace": "Setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c70072ffe0e6e4fdc2374bdf04ba0598\")>\n\n    @pytest.mark.negative\n    def test_login_negative(Setup):\n>       driver = Setup()\nE       TypeError: 'WebDriver' object is not callable\n\ntest_vwo_login.py:22: TypeError"}, "start": 1728029196959, "stop": 1728029196960, "uuid": "17064312-4721-498f-8841-b0ac3ef8a888", "historyId": "8be6628af41c999eb267bfd17245a1df", "testCaseId": "8be6628af41c999eb267bfd17245a1df", "fullName": "tests.vwoLoginTests.test_vwo_login#test_login_negative", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "DESKTOP-O5T1HPJ"}, {"name": "thread", "value": "14296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}